version: "3"

services:
  horilla:
    build: .
    command: ./entrypoint.sh
    working_dir: /horilla
    ports:
      - "8000:8000"
    volumes:
      - ./:/horilla
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}
      - TIME_ZONE=${TIME_ZONE}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_INIT_PASSWORD=${DB_INIT_PASSWORD}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
